services:
  express_frontend:
    build: .
    container_name: express_frontend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      FLASK_SUBMIT_URL: http://host.docker.internal:5000/submittodoitem
